services:
  backend:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - default
    depends_on:
      db:
        condition: service_started
    volumes:
      - .:/app

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${NAME}
    ports:
      - "5432:5432"
    networks:
      - default
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local

networks:
  default:
    driver: bridge